name: isaac-sim 
channels: 
  - defaults
  - pytorch
  - nvidia
dependencies: 
  - python=3.7
  - pip
  - pytorch 
  - torchvision 
  - torchaudio 
  - cuda-toolkit=11.7
  - pip:
    - stable-baselines3==1.6.2
    - tensorboard==2.11.0 
    - tensorboard-plugin-wit==1.8.1 
    - protobuf==3.20.3
