name: isaac-sim
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - pip:
      - stable-baselines3==2.0.0 # TODO: remove unused lib
      - tensorboard==2.11.0
      - tensorboard-plugin-wit==1.8.1
      - protobuf==3.20.3
      - torch-tb-profiler==0.4.3
      - fastparquet==2023.10.1
      - jupyterlab==4.0.9
      - plotly==5.18.0
      - sequitur==1.2.4
      - scikit-learn==1.3.2
