name: isaac-sim
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - cuda-toolkit=11.7
  - pip:
      - stable-baselines3==2.0.0 # TODO: remove unused lib
      - tensorboard==2.11.0
      - tensorboard-plugin-wit==1.8.1
      - protobuf==3.20.3
      - torch-tb-profiler==0.4.3
